ballerina-platform/module-ballerinax-mysql

README.md, mysql-ballerina/src/mysql/tests/query/numerical-query-test.bal
=> Add daily build badge to README

README.md, build.gradle, gradle.properties, mysql-ballerina/Ballerina.toml, mysql-ballerina/build.gradle, mysql-native/build.gradle, mysql-native/src/main/java/org/ballerinalang/mysql/Constants.java, mysql-native/src/main/java/org/ballerinalang/mysql/Utils.java
=> Add stdlib dependencies

README.md, mysql-ballerina/build.gradle, mysql-ballerina/src/mysql/client.bal
Migrating change as per ballerina-lang update in https://github.com/ballerina-platform/ballerina-lang/pull/25228
=> Remove public keyword in function params

mysql-ballerina/src/mysql/client.bal
=> Add Ballerina class support

mysql-ballerina/src/mysql/tests/pool/connection-pool-test.bal
=> Remove lang import

mysql-native/src/main/java/org/ballerinalang/mysql/Constants.java, mysql-native/src/main/java/org/ballerinalang/mysql/NativeImpl.java, mysql-native/src/main/java/org/ballerinalang/mysql/Utils.java
=> Migrate jBallerina Runtime APIs

.github/workflows/pull-request.yml
=> Enable builds from fork

.github/workflows/daily-build.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, build.gradle, mysql-ballerina/Ballerina.toml, mysql-ballerina/build.gradle
=>  Improve release workflow

.gitignore
=> Update gitignore with ballerina lock file

mysql-native/src/main/java/module-info.java, mysql-native/src/main/java/org/ballerinalang/mysql/Constants.java, mysql-native/src/main/java/org/ballerinalang/mysql/NativeImpl.java, mysql-native/src/main/java/org/ballerinalang/mysql/Utils.java
Refactor ballerina runtime api usages
Dependant on https://github.com/ballerina-platform/ballerina-lang/pull/26278
=> Migrate ballerina runtime apis

README.md, mysql-ballerina/build.gradle, mysql-ballerina/src/mysql/tests/procedures/call-procedures-test.bal
$subject as per changes introduced in https://github.com/ballerina-platform/module-ballerina-sql/pull/32
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
=> Migrate test cases to use outparameter types

README.md
$subject
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
=> Update README with latest issues link

mysql-ballerina/tests/local-transaction-test.bal, mysql-ballerina/tests/xa-transactions-test.bal
=> Enable transaction testcases

mysql-ballerina/Package.md, mysql-ballerina/tests/local-transaction-test.bal
$subject as issue https://github.com/ballerina-platform/ballerina-lang/issues/27381 is fixed
=> Reenable test assertions for transactions

.github/workflows/build-master.yml, .github/workflows/pull-request.yml, mysql-ballerina/tests/local-transaction-test.bal
$subject design discussion raised in https://github.com/ballerina-platform/ballerina-standard-library/issues/727
=> Temporarily fix transaction retry test cases

mysql-ballerina/Package.md
=> Fix package toml structure in doc

build.gradle, gradle.properties, mysql-ballerina/tests/batch-execute-query-test.bal, mysql-ballerina/tests/call-procedures-test.bal, mysql-ballerina/tests/execute-basic-test.bal, mysql-ballerina/tests/execute-params-query-test.bal, mysql-ballerina/tests/local-transaction-test.bal
=> Migrate testerina api change

build.gradle, gradle.properties, mysql-ballerina/tests/complex-query-test.bal, mysql-ballerina/tests/connection-pool-test.bal, mysql-ballerina/tests/connection-ssl-test.bal
=> Migrate to regex module

mysql-ballerina/tests/local-transaction-test.bal
> Update tests to sync with marking commit and rollback handler types as isolated
> Link to the PR for changes to the training …
=> Update tests to sync with isolated trx handlers

mysql-ballerina/build.gradle
Update ballerina command to bal command
> Link to the PR for changes to the training content in …
=> Update ballerina command to bal command

mysql-ballerina/tests/local-transaction-test.bal
> Use isolated variable to assert transaction handler execution
> Link to the PR for changes to the training content in …
=> Use isolated var to assert handler execution

mysql-ballerina/Config.toml
$subject
Some config API parts are not migrated due to module-ballerina-auth dependency. 
N/A
N/A
N/A
N/A
[BBE](https://ballerina.io/swan-lake/learn/by-example/configurable.html)
N/A
N/A
N/A
- Unit tests 
>  N/A
- Integration tests
> N/A
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
N/A
> Describe migration steps and platforms on which migration has been tested
jdk-11.0 , ubuntu 20.04
=> Migrate to configurable variables

mysql-ballerina/client.bal
Related Issue: ballerina-platform/ballerina-lang#28034
> Link to the PR for changes to the training content in …
=> Change the name of the `java` langlib module to `jballerina.java`

mysql-ballerina/Ballerina.toml, mysql-ballerina/Dependencies.toml, mysql-ballerina/build.gradle
Fixes ballerina-platform/ballerina-lang#27988
=> Add Dependencies.toml

mysql-ballerina/build.gradle
=> Improve build task to revert depedendency toml

mysql-ballerina/Ballerina.toml, mysql-ballerina/build.gradle
> Renames the extension of the package distribution file from balo to bala 
> Fixes ballerina-platform/ballerina-lang#28476
=> Change ballerina archive extension to bala

README.md, mysql-ballerina/Ballerina.toml, mysql-ballerina/Package.md
> This is to change the URLs consists of /swan-lake/
=> Change the URL links consists of /swan-lake/learn

.github/workflows/publish-release.yml, README.md, gradle.properties, mysql-ballerina/Package.md, mysql-ballerina/build.gradle
> Change string module  to package in Package.md file
=> Change string module -> Package in Package.md

build.gradle, mysql-ballerina/build.gradle
=> Re-order build tasks to enable publishing to central

mysql-ballerina/build.gradle
=> Fix ballerina push not working

mysql-ballerina/tests/complex-query-test.bal, mysql-ballerina/tests/connection-pool-test.bal, mysql-ballerina/tests/local-transaction-test.bal
=> Fix for removal of error type from anydata

build.gradle, gradle.properties
=> Remove reflect stdlib dependency

mysql-ballerina/Config.toml, mysql-ballerina/Package.md, mysql-ballerina/client.bal, mysql-ballerina/tests/connection-init-test.bal, mysql-ballerina/tests/connection-pool-test.bal, mysql-native/src/main/java/org/ballerinalang/mysql/Constants.java, mysql-native/src/main/java/org/ballerinalang/mysql/Utils.java
> $Subject
Fixes: [#967](https://github.com/ballerina-platform/ballerina-standard-library/issues/967)
@shafreenAnfar 
> https://github.com/ballerina-platform/module-ballerina-sql/pull/140
=> Change durations such as timeouts, intervals, etc

mysql-ballerina/build.gradle, mysql-ballerina/tests/init-container.bal
> This PR is to create docker containers for testing from gradle build scripts since exec function is no longer available in module-ballerina-os package. 
> Enable Docker container creation for testing.
> Link to the PR for changes …
=> Create Docker container for testing from gradle scripts

mysql-ballerina/build.gradle
> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763
=> Add extracted bala in the zip artifact

mysql-ballerina/build.gradle
Filter only package native classes and ballerina classes for test coverage report using includes flag.
Fixes ballerina-platform/ballerina-lang#28951
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …
=> Add specific includes for code coverage

mysql-ballerina/build.gradle
> Add -c flag to build command
> Related to ballerina-platform/ballerina-lang#29032
=> Add -c flag to build command

gradle.properties, mysql-ballerina/Ballerina.toml, mysql-ballerina/build.gradle, mysql-ballerina/tests/complex-query-test.bal
=> Migrate time & task dependencies

mysql-ballerina/client.bal
> $Subject 
> provide isolated APIs to db client module users.
>https://github.com/ballerina-platform/module-ballerina-sql/pull/151
=> Change module APIs to isolated

mysql-ballerina/Package.md
> $subject
Fixes: [#1120](https://github.com/ballerina-platform/ballerina-standard-library/issues/1120)
> artafactId corrected to artifactId
=> Fix typo in Package.md

README.md, mysql-ballerina/build.gradle
=> Add configs to publish to local repository

.github/workflows/publish-release.yml, mysql-ballerina/build.gradle
=> Fix maven publishing failing

.github/workflows/build-master.yml, .github/workflows/publish-release.yml, README.md, mysql-ballerina/build.gradle
=> Use separate config for Github package publish

build.gradle, mysql-ballerina/build.gradle
=> Strip stdlib dependency version

mysql-ballerina/client.bal
$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1160
=> Add details to doc for return type of the query remote function

mysql-ballerina/tests/Config.toml
=> Bug fix in Config.toml file

mysql-ballerina/build.gradle
Set flag to enable Jacoco Coverage XML generation. Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30381
=> Set flag to enable Jacoco Coverage XML generation

README.md, mysql-ballerina/Module.md, mysql-ballerina/Package.md, mysql-ballerina/client.bal
=> Improve the API docs, module MD, and package MD

mysql-ballerina/build.gradle
Update flag for coverage format from '--jacoco-xml' to '--coverage-format=xml'
=> Update flag for coverage format

changelog.md, gradle.properties, mysql-ballerina/client.bal
$Title
https://github.com/ballerina-platform/module-ballerina-sql/pull/245
https://github.com/ballerina-platform/module-ballerinax-java.jdbc/pull/175
Fixes:
=> Make the db client class isolated

gradle.properties
=> Update ballerina plugin verion

mysql-ballerina/client.bal, mysql-ballerina/tests/call-procedures-test.bal, mysql-ballerina/tests/connection-pool-test.bal, mysql-ballerina/tests/local-transaction-test.bal, mysql-ballerina/tests/simple-params-query-test.bal, mysql-ballerina/tests/utils.bal, mysql-ballerina/tests/xa-transactions-test.bal
=> Remove taint checks

changelog.md, gradle.properties, mysql-ballerina/client.bal, mysql-ballerina/tests/numerical-query-test.bal, mysql-ballerina/tests/simple-params-query-test.bal, mysql-native/src/main/java/org/ballerinalang/mysql/nativeimpl/QueryProcessor.java
$title
Fixes for:
https://github.com/ballerina-platform/ballerina-standard-library/issues/1445
https://github.com/ballerina-platform/module-ballerina-sql/pull/264
=> Change Return stream type of the query remote method

mysql-ballerina/Package.md
$Subject
Related issue: ballerina-platform/ballerina-standard-library#1462
=> Update Package.md links into HTML format

mysql-ballerina/Module.md
$title
Fix for: https://github.com/ballerina-platform/ballerina-standard-library/issues/1463
=> Improve API docs

mysql-ballerina/client.bal, mysql-native/src/main/java/org/ballerinalang/mysql/Constants.java, mysql-native/src/main/java/org/ballerinalang/mysql/Utils.java
=> Refactor code

mysql-ballerina/Module.md, mysql-ballerina/client.bal
$Subject
Related issue: [1537](https://github.com/ballerina-platform/ballerina-standard-library/issues/1537), [1515](https://github.com/ballerina-platform/ballerina-standard-library/issues/1515) & [1539](https://github.com/ballerina-platform/ballerina-standard-library/issues/1539)
=> Fix doc issues

mysql-ballerina/Module.md
Fix invalid sample codes in Module.md
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1633
=> Fix Invalid samples in Module.md

gradle.properties, native/src/main/java/io/ballerina/stdlib/mysql/parameterprocessor/MysqlResultParameterProcessor.java
Migrates to latest SQL dependency
Depends on https://github.com/ballerina-platform/module-ballerina-sql/pull/311
=> Improve abstraction of SQL native code

ballerina/client.bal, ballerina/tests/call-procedures-test.bal, ballerina/tests/complex-query-test.bal, ballerina/tests/connection-pool-test.bal, ballerina/tests/execute-basic-test.bal, ballerina/tests/local-transaction-test.bal, ballerina/tests/numerical-query-test.bal, ballerina/tests/simple-params-query-test.bal, ballerina/tests/xa-transactions-test.bal, changelog.md, gradle.properties
$title
Related issue ballerina-platform/ballerina-standard-library#1654
=> Add completion type as nil in SQL query return stream type

ballerina/client.bal, ballerina/tests/simple-params-query-test.bal, changelog.md, gradle.properties, native/src/main/java/io/ballerina/stdlib/mysql/nativeimpl/QueryProcessor.java
$subject
Related issue: ballerina-platform/ballerina-standard-library#1604
=> Add support for query row

gradle.properties, native/src/main/java/io/ballerina/stdlib/mysql/nativeimpl/CallProcessor.java, native/src/main/java/io/ballerina/stdlib/mysql/nativeimpl/ExecuteProcessor.java, native/src/main/java/io/ballerina/stdlib/mysql/nativeimpl/QueryProcessor.java
=> Migrate to latest version of SQL dependency

gradle.properties, native/src/main/java/io/ballerina/stdlib/mysql/nativeimpl/ClientProcessor.java
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/1808
=> Add auto generated keys retrieval flags

ballerina/tests/simple-params-query-test.bal, gradle.properties, native/src/main/java/io/ballerina/stdlib/mysql/parameterprocessor/MysqlResultParameterProcessor.java
$subject. The changes come from SQL dependency
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/1807
=> Improve error types

.github/workflows/publish-release.yml, .gitignore, ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/build.gradle, build-config/resources/Ballerina.toml, gradle.properties
$title
Related issue: ballerina-platform/ballerina-standard-library#1746
=> Make the Ballerina Project Tooling Friendly

README.md, ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/client.bal, ballerina/tests/simple-params-query-test.bal, gradle.properties, native/src/main/java/io/ballerina/stdlib/mysql/nativeimpl/QueryProcessor.java
$subject due to SQL module change https://github.com/ballerina-platform/module-ballerina-sql/pull/376
Fixes:
=> Remove string usages from queryRow and batchUpdate

ballerina/Module.md
$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/1914
Similar PR: https://github.com/ballerina-platform/module-ballerina-sql/pull/379
=> Update module.md with queryRow() documentation

.github/workflows/build-timestamped-master.yml, .github/workflows/publish-release.yml, .github/workflows/trivy-scan.yml, README.md
$title
Related issue:  ballerina-platform/ballerina-standard-library#1849
=> Add trivy scan for release builds and add daily trivy scan build

ballerina/Module.md, ballerina/tests/call-procedures-test.bal, ballerina/tests/complex-query-test.bal, ballerina/tests/connection-pool-test.bal, ballerina/tests/execute-basic-test.bal, ballerina/tests/execute-params-query-test.bal, ballerina/tests/local-transaction-test.bal, ballerina/tests/numerical-query-test.bal, ballerina/tests/simple-params-query-test.bal, ballerina/tests/xa-transactions-test.bal
$subject part of ballerina-platform/ballerina-standard-library#1880
=> Convert all string queries usages to parameterized queries in tests

ballerina/Ballerina.toml, build-config/resources/Ballerina.toml
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2051
N/A
=> Enrich Ballerina.toml with package properties

ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/tests/call-procedures-test.bal, ballerina/tests/complex-query-test.bal, ballerina/tests/connection-pool-test.bal, ballerina/tests/execute-params-query-test.bal, ballerina/tests/local-transaction-test.bal, ballerina/tests/numerical-query-test.bal, ballerina/tests/simple-params-query-test.bal, ballerina/tests/xa-transactions-test.bal
=> Fix unused variables warning in tests

ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/client.bal, changelog.md, gradle.properties
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2390
To be merged after: https://github.com/ballerina-platform/module-ballerina-sql/pull/441
=> Change queryRow() API accept anydata as the return-type instead of any

gradle.properties
$subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/2396
N/A
=> Update ballerina gradle plugin version

load-tests/delete/deployment/ingress.yaml, load-tests/delete/results/summary.csv, load-tests/delete/scripts/run.sh, load-tests/insert/deployment/ingress.yaml, load-tests/insert/results/summary.csv, load-tests/insert/scripts/run.sh, load-tests/select/deployment/ingress.yaml, load-tests/select/results/summary.csv, load-tests/select/scripts/run.sh, load-tests/update/deployment/ingress.yaml, load-tests/update/results/summary.csv, load-tests/update/scripts/run.sh
$subject
Related issue: ballerina-platform/ballerina-standard-library#2270
=> Change services names in ingress.yaml files and change port numbers in load tests

ballerina/Ballerina.toml, ballerina/tests/error.bal
$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2297
=> Add missing negative test cases

ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/client.bal, ballerina/tests/batch-execute-query-test.bal, ballerina/tests/call-procedures-test.bal, ballerina/tests/complex-query-test.bal, ballerina/tests/connection-init-test.bal, ballerina/tests/connection-pool-test.bal, ballerina/tests/connection-ssl-test.bal, ballerina/tests/error.bal, ballerina/tests/execute-basic-test.bal, ballerina/tests/execute-params-query-test.bal, ballerina/tests/local-transaction-test.bal, ballerina/tests/numerical-query-test.bal, ballerina/tests/simple-params-query-test.bal, ballerina/tests/utils.bal, ballerina/tests/xa-transactions-test.bal, ballerina/types.bal
$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2275
N/A
=> Refactor code by removing anti pattern usages

ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/tests/complex-query-test.bal, ballerina/tests/numerical-query-test.bal, examples/employees-db/README.md, examples/employees-db/service/service.bal
$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2592
=> Use query syntax instead of foreach

docs/spec/spec.md
=> Improve specification description

docs/spec/spec.md
=> Fix specification link

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, changelog.md, compiler-plugin-tests/src/test/java/io/ballerina/stdlib/mysql/compiler/CompilerPluginTest.java, compiler-plugin-tests/src/test/resources/diagnostics/sample4/Ballerina.toml, compiler-plugin-tests/src/test/resources/diagnostics/sample4/main.bal, compiler-plugin/src/main/java/io/ballerina/stdlib/mysql/compiler/Utils.java, compiler-plugin/src/main/java/io/ballerina/stdlib/mysql/compiler/analyzer/InitializerParamAnalyzer.java, gradle.properties
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2625
Added fixes:
https://github.com/ballerina-platform/module-ballerinax-mysql/pull/326
=> Patch release for MySQL 1.2.1

docs/spec/spec.md
=> Improve spec introduction

.github/workflows/process-load-test-result.yml
=> Add logic for PR failures

.github/pull_request_template.md, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/trivy-scan.yml
$subject 
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2483
=> Update workflows with create lib folder step

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, changelog.md, gradle.properties
Reverts ballerina-platform/module-ballerinax-mysql#387
=> Revert "[Automated] Sync master after 1.3.1 release"

ballerina/Ballerina.toml, build-config/resources/Ballerina.toml
=> Update to `2201.0.1` patch distribution

ballerina/Ballerina.toml, ballerina/Dependencies.toml, gradle.properties
=> Update lang version to 2201.0.1

README.md, ballerina/Module.md, ballerina/Package.md, docs/spec/spec.md
$subject
Fixes:
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2748
=> Update doc titles with sentence case and remove -ing

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, changelog.md, gradle.properties
=> Move version to next minor version

ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/client.bal, changelog.md, gradle.properties
$subject
And Corrects incorrect code snippet relates to https://github.com/ballerina-platform/ballerina-standard-library/issues/2931
=> Update to latest dependency version

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, gradle.properties
=> Update SQL version

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, ballerina/build.gradle, ballerina/tests/complex-query-test.bal, ballerina/tests/connection-ssl-test.bal, changelog.md, examples/employees-db/service/Ballerina.toml, examples/employees-db/setup/Ballerina.toml, gradle.properties, native/src/main/java/io/ballerina/stdlib/mysql/parameterprocessor/MysqlResultParameterProcessor.java
$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3023
=> Update MySQL driver version to 8.0.29

.github/workflows/central-publish.yml
$subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/3136
=> Improve workflow to publish snapshots

ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/build.gradle, build-config/resources/Ballerina.toml, build.gradle, gradle.properties
$subject part of https://github.com/ballerina-platform/ballerina-standard-library/issues/3128
Fixes:
=> Update dependencies to latest version

ballerina/Ballerina.toml, build-config/resources/Ballerina.toml
$subject 
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/3117
=> Add details for dependant jars

README.md, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, ballerina/Package.md, build-config/resources/Ballerina.toml, build.gradle, changelog.md, docs/spec/spec.md, gradle.properties
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3463
=> Bump to update 3 dependencies

ballerina/Ballerina.toml, ballerina/build.gradle, ballerina/tests/xa-transactions-test.bal
=> Improve XA transaction test cases to use 2 data sources

gradle.properties
$subject
Related to https://github.com/ballerina-platform/plugin-gradle/issues/81
=> Update gradle plugin to disable offline mode

compiler-plugin/src/main/java/io/ballerina/stdlib/mysql/compiler/Constants.java, compiler-plugin/src/main/java/io/ballerina/stdlib/mysql/compiler/Utils.java, compiler-plugin/src/main/java/io/ballerina/stdlib/mysql/compiler/analyzer/InitializerParamAnalyzer.java, compiler-plugin/src/main/java/io/ballerina/stdlib/mysql/compiler/analyzer/RecordAnalyzer.java
=> Improve compiler error check before analysing

README.md, ballerina/Module.md, ballerina/Package.md, ballerina/client.bal
=> Update docs with suggested changes

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, changelog.md, compiler-plugin-tests/build.gradle, compiler-plugin-tests/src/test/java/io/ballerina/stdlib/mysql/compiler/CompilerPluginTest.java, compiler-plugin-tests/src/test/resources/diagnostics/sample5/Ballerina.toml, compiler-plugin-tests/src/test/resources/diagnostics/sample5/main.bal, compiler-plugin-tests/src/test/resources/diagnostics/sample5/tests/tests.bal, compiler-plugin/src/main/java/io/ballerina/stdlib/mysql/compiler/analyzer/RemoteMethodAnalyzer.java
$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4054
=> Fix compiler plugin failure when the diagnostic code is null

.github/workflows/process-load-test-result.yml, .github/workflows/pull-request.yml, .github/workflows/trigger-load-tests.yml
$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4098
=> Add workflow calls to load tests

.github/workflows/pull-request.yml, .github/workflows/trigger-load-tests.yml
=> Fix indentation

.github/workflows/pull-request.yml
=> Add codecov token to pr build

ballerina/Dependencies.toml, compiler-plugin-tests/build.gradle, compiler-plugin/src/main/java/io/ballerina/stdlib/mysql/compiler/Constants.java, compiler-plugin/src/main/java/io/ballerina/stdlib/mysql/compiler/Utils.java, gradle.properties
$subject
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/3119
N/A
=> Enable code coverage for compiler plugin

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
=> Update dependency version for update 5

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build.gradle, gradle.properties
$Subject 
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4382
=> Remove regex usages

changelog.md, gradle.properties
$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/4588
=> Update dependency versions for U7 and support enum type retreival

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/daily-build.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml, README.md, ballerina/Ballerina.toml, ballerina/Module.md, ballerina/Package.md, build-config/checkstyle/build.gradle, build-config/resources/Ballerina.toml, build-config/spotbugs-exclude.xml, compiler-plugin-tests/build.gradle, examples/employees-db/README.md, gradle.properties, gradle/wrapper/gradle-wrapper.properties, native/build.gradle, native/src/main/java/io/ballerina/stdlib/mysql/Constants.java
=> Migrate to Java 17

ballerina/Ballerina.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
=> Bump minor versions and update distribution

examples/employees-db/Working with a MySQL Database.md
=> Update example readme

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
Please note the $subject.
Fixes:
=> Bump version and update dependencies for Update 9

ballerina/tests/connection-ssl-test.bal
=> Update ssl error message

.github/workflows/build-timestamped-master.yml, .github/workflows/build-with-bal-test-graalvm.yml, .github/workflows/central-publish.yml, .github/workflows/daily-build.yml, .github/workflows/process-load-test-result.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trigger-load-tests.yml, .github/workflows/trivy-scan.yml, README.md, ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/tests/call-procedures-test.bal, ballerina/tests/resources/Dockerfile, build-config/resources/Ballerina.toml, compiler-plugin-tests/build.gradle, compiler-plugin/build.gradle, gradle.properties, native/build.gradle
=> Migrate to Java 21

ballerina/Dependencies.toml, ballerina/cdc_listener.bal, ballerina/types.bal
=> Tweak type descriptions
